# Generated by Django 5.2.1 on 2025-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('WARM', 'Warm Up'), ('SCAL', 'Scales'), ('SONG', 'Song Training'), ('TECH', 'Technique'), ('OTHE', 'Other')], max_length=4)),
                ('description', models.TextField()),
                ('time', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
